apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: 905418306644.dkr.ecr.eu-central-1.amazonaws.com/todo-app
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred

